#!/bin/bash
set -eu

if [ ! -d "$HOME" ] ; then echo "Not found: $HOME" ; exit 1 ; fi
ETC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

link () {
  FROM="$ETC/$1"
  if [ ! -e "$FROM" ] ; then echo "Not found: $FROM" ; exit 1 ; fi
  TO="$HOME/$1"
  if [ ! -e "$TO" ] ; then
    echo "Linking: $TO --> $FROM"
    pushd "$(dirname "$TO")" > /dev/null
    ln -s "$FROM"
    popd > /dev/null
  else
    echo "Exists: $TO"
  fi
}

link ".aliases"
link ".SciTEUser.properties"
link ".tmux.conf"
link ".zprofile"
link ".zshenv"
link ".zshrc"
link ".vimrc"
link ".screenrc"
link ".profile"

if [ "$(uname)" = "Darwin" ] ; then
  mkdir -p "$HOME/Library/Application Support/KeyRemap4MacBook"
  link "Library/Application Support/KeyRemap4MacBook/private.xml"
fi

mkdir -p "$HOME/.vimswp"

if ! [ -e "$HOME/.zsh_history" ] ; then
  echo "Using bash history as initial zsh history."
  cp -v "$HOME/.bash_history" "$HOME/.zsh_history"
fi
