#!/usr/bin/env bash
set -eu

if [ ! -d "$HOME" ] ; then echo "Not found: $HOME" ; exit 1 ; fi
ETC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

link() {
  FROM="$ETC/$1"
  if [ ! -e "$FROM" ] ; then echo "Not found: $FROM" ; exit 1 ; fi
  TO="$HOME/$1"
  if ! [ -e "$TO" ] ; then
    echo "Linking: $TO --> $FROM"
    pushd "$(dirname "$TO")" > /dev/null
    ln -s "$FROM"
    popd > /dev/null
  else
    echo "Exists: $TO"
  fi
}

link ".aliases"
link ".tmux.conf"
link ".zprofile"
link ".zshenv"
link ".zshrc"
link ".zlogout"
link ".vimrc"
link ".screenrc"
link ".profile"

mkdir -p "$HOME/.vimperator"
link ".vimperatorrc"
link ".vimperator/colors"

if [ "$(uname)" = "Darwin" ] ; then
  mkdir -p "$HOME/Library/Application Support/Karabiner"
  link "Library/Application Support/Karabiner/private.xml"
fi

mkdir -p "$HOME/.vimswp"
mkdir -p "$HOME/.vim/colors/"
link ".vim/colors/faerie.vim"

if ! [ -e "$HOME/.zsh_history" ] && [ -e "$HOME/.bash_history" ] ; then
  echo "Using bash history as initial zsh history."
  cp -v "$HOME/.bash_history" "$HOME/.zsh_history"
fi
